### ISSUE TITLE
Makefile is inconsistent, lacks a way to uninstall, and forces a certain build directory

### ISSUE THREAD

**Issue by buffet** [Sweets/custard#21]
If you want I could improve the Makefile a little by

1. Making the syntax a little more consistent, and cleaning up a little
2. Adding an uninstall target
3. Allowing VPATH driven out of source builds (similar to what kiwmi does atm), instead of forcing a `build/` directory. This allows for a cleaner Makefile and an easier way to build multiple targets (multiple architectures, debug and release build, etc).

Just tell me what you want, if any.

**Comment by Sweets** [comment]
Feel free to open a pull request with all of the above.
A Makefile for bmake would be convenient, if you can, but if you can't (or don't feel like it) don't worry about it (the reason I bring this up is because it's a pain to compile custard on OpenBSD currently, and I would imagine other BSD based operating systems as well).

**Comment by buffet** [comment]
Fixed with #23.
