### ISSUE TITLE
Where custardctl binary?

### ISSUE THREAD

**Issue by BartolomeyKant** [Sweets/custard#31]
I clone repository and do `make` and `make install`. And I don't have `custardctl` in my system.

**Comment by Sweets** [comment]
Non-existent, custardctl was removed a very long time ago in favor of `custard - `. If there's anywhere that says you need it, let me know though, because that's in need of being updated

**Comment by BartolomeyKant** [comment]
I saw it in examples. And there is no examples for using `custard - `. Also I trying replace `custardctl` by `custard` and it didn't work for me. I tryed moving windows. But switching workspaces and closing windows works well.

**Comment by Sweets** [comment]
My mistake, I see it in the example sxhkdrc. I'll fix that as soon as I can. As for moving and raising/lower, the syntax has changed for those. Window moving itself has been taken out, but is planned to be added back in (it was removed due to a rewrite; just haven't gotten around to it yet). Currently, window matching is the only way to set a window's geometry (again, soon to change once I add the movement and resizing commands back)

https://github.com/Sweets/custard/wiki/Window-Management

**Comment by BartolomeyKant** [comment]
I am using 2bwm now. I hoped that custard have the same window movement (resizing) possibilities. Can I moving windows by `super + button1+mouse drag` like in 2bwm?

**Comment by Sweets** [comment]
Re-added contract and expand commands. As for mouse movement, unfortunately, not at this time. I've considered adding it, just one of those "haven't gotten to it" things. Though I'm not sure I would because custard is supposed to be manual tiling.

https://github.com/Sweets/custard/commit/65712b81905bbf64bb4d876be21d74d23bfb85eb

**Comment by trvv** [comment]
Is this closed?
